"""mTLS termination: peer-cert extraction, validation, and the ``require_mtls`` dependency.

Mirrors `dprox-design-spec-v0.2.md` §3 (trust model), §4.3 (error short codes),
§7.2 (mTLS implementation), and `dprox-cert-integration-v0.2.md` (runtime
contract).

Architecture:
    1. ``DproxHttpProtocol`` — uvicorn HTTP protocol subclass that injects the
       verified peer cert (DER bytes) into ``scope["client_cert_der"]`` on
       every request. uvicorn 0.46 does not populate the ASGI TLS extension,
       so we do this ourselves.
    2. ``validate_client_cert`` — parses DER bytes, enforces EKU=clientAuth
       and exactly one CN attribute. Pure function; unit-testable.
    3. ``require_mtls`` — FastAPI dependency that reads the scope key, runs
       ``validate_client_cert``, stashes ``cn`` and ``cert_serial`` on
       ``request.state``, returns the CN string. Apply only to ``/v1/query``.
"""

from __future__ import annotations

from typing import Any

from cryptography import x509
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID
from fastapi import Request
from uvicorn.protocols.http.httptools_impl import HttpToolsProtocol

# Scope key used by the protocol → dependency contract.
SCOPE_KEY = "client_cert_der"


class AuthFailure(Exception):
    """Raised by ``require_mtls`` when peer-cert validation fails.

    Maps to one of the spec §4.3 error responses. The exception handler
    registered in ``server.create_app`` flattens this to the spec's
    ``{"error": <code>, "message": <text>}`` shape — distinct from
    FastAPI's default ``{"detail": ...}`` envelope.
    """

    def __init__(self, code: str, message: str, status: int = 401) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status = status


def validate_client_cert(der: bytes | None) -> tuple[str, str]:
    """Validate a peer cert and return ``(cn, cert_serial_hex)``.

    Performs the four checks from spec §7.2:
        1. cert present                 → 401 ``auth_required`` if absent
        2. cert parses                  → 401 ``cert_invalid`` on parse failure
        3. ``extKeyUsage`` clientAuth   → 401 ``cert_invalid`` if missing
        4. Subject contains exactly 1 CN → 401 ``cn_unparseable`` otherwise

    Pure function — does not touch any framework state. Unit-testable
    against synthetic certs generated by ``cryptography``.
    """
    if der is None:
        raise AuthFailure("auth_required", "no client cert presented")

    try:
        cert = x509.load_der_x509_certificate(der)
    except Exception as exc:
        raise AuthFailure(
            "cert_invalid", f"could not parse client cert: {exc.__class__.__name__}"
        ) from exc

    # extKeyUsage must include clientAuth — defence in depth (Python's ssl
    # module does not enforce EKU). Without this check, a server cert
    # signed by the same CA could authenticate as a client.
    try:
        eku = cert.extensions.get_extension_for_class(x509.ExtendedKeyUsage)
    except x509.ExtensionNotFound:
        raise AuthFailure(
            "cert_invalid", "client cert has no extKeyUsage extension"
        ) from None

    if ExtendedKeyUsageOID.CLIENT_AUTH not in eku.value:
        raise AuthFailure(
            "cert_invalid", "client cert extKeyUsage does not include clientAuth"
        )

    # Subject must have exactly one CN attribute. The platform CA emits
    # single-CN subjects (cert-integration v0.2 §"What the certs look like");
    # multi-CN means a misissued or hostile cert.
    cn_attrs = cert.subject.get_attributes_for_oid(NameOID.COMMON_NAME)
    if len(cn_attrs) == 0:
        raise AuthFailure(
            "cn_unparseable", "client cert subject has no CN attribute"
        )
    if len(cn_attrs) > 1:
        raise AuthFailure(
            "cn_unparseable",
            f"client cert subject has {len(cn_attrs)} CN attributes (expected 1)",
        )

    cn_value = cn_attrs[0].value
    if not isinstance(cn_value, str):
        # cryptography returns str for utf8/printable, bytes for others.
        # Don't try to coerce — it's a misissued cert if CN isn't a string.
        raise AuthFailure(
            "cn_unparseable", "client cert CN is not a printable string"
        )

    return cn_value, format(cert.serial_number, "x")


def require_mtls(request: Request) -> str:
    """FastAPI dependency. Apply to ``/v1/query`` only.

    Reads the DER cert injected by ``DproxHttpProtocol`` from the ASGI
    scope, validates it, stashes ``cn`` and ``cert_serial`` on
    ``request.state`` for handlers and audit logging, and returns the CN.
    """
    der = request.scope.get(SCOPE_KEY)
    cn, serial = validate_client_cert(der)
    request.state.cn = cn
    request.state.cert_serial = serial
    return cn


class DproxHttpProtocol(HttpToolsProtocol):
    """uvicorn HTTP protocol that surfaces the peer cert on the ASGI scope.

    uvicorn 0.46 only sets ``scope["scheme"] = "https"`` from SSL state.
    To enforce mTLS at the FastAPI dependency layer we need the actual
    DER bytes in scope; this subclass writes them on every request.

    On a non-TLS connection (or no client cert presented under
    ``CERT_OPTIONAL``), ``client_cert_der`` is ``None`` — the dependency
    on ``/v1/query`` raises ``auth_required`` while ``/healthz`` and
    ``/version`` ignore the scope key entirely.
    """

    def on_message_begin(self) -> None:  # pragma: no cover — tested via integration
        super().on_message_begin()
        ssl_obj = self.transport.get_extra_info("ssl_object")
        if ssl_obj is None:
            self.scope[SCOPE_KEY] = None
            return
        try:
            self.scope[SCOPE_KEY] = ssl_obj.getpeercert(binary_form=True)
        except ValueError:
            # Handshake not finished, or peer cert unavailable for some
            # reason. Treat as "no cert".
            self.scope[SCOPE_KEY] = None


def auth_failure_to_dict(exc: AuthFailure) -> dict[str, Any]:
    """Flatten an ``AuthFailure`` into the spec §4.3 error body shape."""
    return {"error": exc.code, "message": exc.message}
